version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: video-api
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./data:/app/data           # שומר פלטים/קבצים גם מחוץ לקונטיינר
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
